import { ethers } from "ethers";

export interface SurahRawMetadata {
  index: number;
  name: string;
  englishName: string;
  verses: number;
  type: "Meccan" | "Medinan";
  hash: string;
}

// Full array of 114 Surahs with metadata and pre-calculated deterministic Keccak256 hashes
// The hashes are calculated based on their indices, names, verse counts, and standard descriptors to ensure local verification matches
export const quranMetadataList: SurahRawMetadata[] = [
  { index: 1, name: "الفاتحة", englishName: "Al-Fatihah", verses: 7, type: "Meccan", hash: "" },
  { index: 2, name: "البقرة", englishName: "Al-Baqarah", verses: 286, type: "Medinan", hash: "" },
  { index: 3, name: "آل عمران", englishName: "Ali 'Imran", verses: 200, type: "Medinan", hash: "" },
  { index: 4, name: "النساء", englishName: "An-Nisa", verses: 176, type: "Medinan", hash: "" },
  { index: 5, name: "المائدة", englishName: "Al-Ma'idah", verses: 120, type: "Medinan", hash: "" },
  { index: 6, name: "الأنعام", englishName: "Al-An'am", verses: 165, type: "Meccan", hash: "" },
  { index: 7, name: "الأعراف", englishName: "Al-A'raf", verses: 206, type: "Meccan", hash: "" },
  { index: 8, name: "الأنفال", englishName: "Al-Anfal", verses: 75, type: "Medinan", hash: "" },
  { index: 9, name: "التوبة", englishName: "At-Tawbah", verses: 129, type: "Medinan", hash: "" },
  { index: 10, name: "يونس", englishName: "Yunus", verses: 109, type: "Meccan", hash: "" },
  { index: 11, name: "هود", englishName: "Hud", verses: 123, type: "Meccan", hash: "" },
  { index: 12, name: "يوسف", englishName: "Yusuf", verses: 111, type: "Meccan", hash: "" },
  { index: 13, name: "الرعد", englishName: "Ar-Ra'd", verses: 43, type: "Medinan", hash: "" },
  { index: 14, name: "إبراهيم", englishName: "Ibrahim", verses: 52, type: "Meccan", hash: "" },
  { index: 15, name: "الحجر", englishName: "Al-Hijr", verses: 99, type: "Meccan", hash: "" },
  { index: 16, name: "النحل", englishName: "An-Nahl", verses: 128, type: "Meccan", hash: "" },
  { index: 17, name: "الإسراء", englishName: "Al-Isra", verses: 111, type: "Meccan", hash: "" },
  { index: 18, name: "الكهف", englishName: "Al-Kahf", verses: 110, type: "Meccan", hash: "" },
  { index: 19, name: "مريم", englishName: "Maryam", verses: 98, type: "Meccan", hash: "" },
  { index: 20, name: "طه", englishName: "Taha", verses: 135, type: "Meccan", hash: "" },
  { index: 21, name: "النبياء", englishName: "Al-Anbiya", verses: 112, type: "Meccan", hash: "" },
  { index: 22, name: "الحج", englishName: "Al-Hajj", verses: 78, type: "Medinan", hash: "" },
  { index: 23, name: "المؤمنون", englishName: "Al-Mu'minun", verses: 118, type: "Meccan", hash: "" },
  { index: 24, name: "النور", englishName: "An-Nur", verses: 64, type: "Medinan", hash: "" },
  { index: 25, name: "الفرقان", englishName: "Al-Furqan", verses: 77, type: "Meccan", hash: "" },
  { index: 26, name: "الشعراء", englishName: "Ash-Shu'ara", verses: 227, type: "Meccan", hash: "" },
  { index: 27, name: "النمل", englishName: "An-Naml", verses: 93, type: "Meccan", hash: "" },
  { index: 28, name: "القصص", englishName: "Al-Qasas", verses: 88, type: "Meccan", hash: "" },
  { index: 29, name: "العنكبوت", englishName: "Al-'Ankabut", verses: 69, type: "Meccan", hash: "" },
  { index: 30, name: "الروم", englishName: "Ar-Rum", verses: 60, type: "Meccan", hash: "" },
  { index: 31, name: "لقمان", englishName: "Luqman", verses: 34, type: "Meccan", hash: "" },
  { index: 32, name: "السجدة", englishName: "As-Sajdah", verses: 30, type: "Meccan", hash: "" },
  { index: 33, name: "الأحزاب", englishName: "Al-Ahzab", verses: 73, type: "Medinan", hash: "" },
  { index: 34, name: "سبأ", englishName: "Saba", verses: 54, type: "Meccan", hash: "" },
  { index: 35, name: "فاطر", englishName: "Fatir", verses: 45, type: "Meccan", hash: "" },
  { index: 36, name: "يس", englishName: "Ya-Sin", verses: 83, type: "Meccan", hash: "" },
  { index: 37, name: "الصافات", englishName: "As-Saffat", verses: 182, type: "Meccan", hash: "" },
  { index: 38, name: "ص", englishName: "Sad", verses: 88, type: "Meccan", hash: "" },
  { index: 39, name: "الزمر", englishName: "Az-Zumar", verses: 75, type: "Meccan", hash: "" },
  { index: 40, name: "غافر", englishName: "Ghafir", verses: 85, type: "Meccan", font: "Amiri", hash: "" } as any,
  { index: 41, name: "فصلت", englishName: "Fussilat", verses: 54, type: "Meccan", hash: "" },
  { index: 42, name: "الشورى", englishName: "Ash-Shura", verses: 53, type: "Meccan", hash: "" },
  { index: 43, name: "الزخرف", englishName: "Az-Zukhruf", verses: 89, type: "Meccan", hash: "" },
  { index: 44, name: "الدخان", englishName: "Ad-Dukhan", verses: 59, type: "Meccan", hash: "" },
  { index: 45, name: "الجاثية", englishName: "Al-Jathiyah", verses: 37, type: "Meccan", hash: "" },
  { index: 46, name: "الأحقاف", englishName: "Al-Ahqaf", verses: 35, type: "Meccan", hash: "" },
  { index: 47, name: "محمد", englishName: "Muhammad", verses: 38, type: "Medinan", hash: "" },
  { index: 48, name: "الفتح", englishName: "Al-Fath", verses: 29, type: "Medinan", hash: "" },
  { index: 49, name: "الحجرات", englishName: "Al-Hujurat", verses: 18, type: "Medinan", hash: "" },
  { index: 50, name: "ق", englishName: "Qaf", verses: 45, type: "Meccan", hash: "" },
  { index: 51, name: "الذاريات", englishName: "Adh-Dhariyat", verses: 60, type: "Meccan", hash: "" },
  { index: 52, name: "الطور", englishName: "At-Tur", verses: 49, type: "Meccan", hash: "" },
  { index: 53, name: "النجم", englishName: "An-Najm", verses: 62, type: "Meccan", hash: "" },
  { index: 54, name: "القمر", englishName: "Al-Qamar", verses: 55, type: "Meccan", hash: "" },
  { index: 55, name: "الرحمن", englishName: "Ar-Rahman", verses: 78, type: "Medinan", hash: "" },
  { index: 56, name: "الواقعة", englishName: "Al-Waqi'ah", verses: 96, type: "Meccan", hash: "" },
  { index: 57, name: "الحديد", englishName: "Al-Hadid", verses: 29, type: "Medinan", hash: "" },
  { index: 58, name: "المجادلة", englishName: "Al-Mujadilah", verses: 22, type: "Medinan", hash: "" },
  { index: 59, name: "الحشر", englishName: "Al-Hashr", verses: 24, type: "Medinan", hash: "" },
  { index: 60, name: "الممتحنة", englishName: "Al-Mumtahanah", verses: 13, type: "Medinan", hash: "" },
  { index: 61, name: "الصف", englishName: "As-Saff", verses: 14, type: "Medinan", hash: "" },
  { index: 62, name: "الجمعة", englishName: "Al-Jumu'ah", verses: 11, type: "Medinan", hash: "" },
  { index: 63, name: "المنافقون", englishName: "Al-Munafiqun", verses: 11, type: "Medinan", hash: "" },
  { index: 64, name: "التغابن", englishName: "At-Taghabun", verses: 18, type: "Medinan", hash: "" },
  { index: 65, name: "الطلاق", englishName: "At-Talaq", verses: 12, type: "Medinan", hash: "" },
  { index: 66, name: "التحريم", englishName: "At-Tahrim", verses: 12, type: "Medinan", hash: "" },
  { index: 67, name: "الملك", englishName: "Al-Mulk", verses: 30, type: "Meccan", hash: "" },
  { index: 68, name: "القلم", englishName: "Al-Qalam", verses: 52, type: "Meccan", hash: "" },
  { index: 69, name: "الحاقة", englishName: "Al-Haqqah", verses: 52, type: "Meccan", hash: "" },
  { index: 70, name: "المعارج", englishName: "Al-Ma'arij", verses: 44, type: "Meccan", hash: "" },
  { index: 71, name: "نوح", englishName: "Nuh", verses: 28, type: "Meccan", hash: "" },
  { index: 72, name: "الجن", englishName: "Al-Jinn", verses: 28, type: "Meccan", hash: "" },
  { index: 73, name: "المزمل", englishName: "Al-Muzzammil", verses: 20, type: "Meccan", hash: "" },
  { index: 74, name: "المدثر", englishName: "Al-Muddaththir", verses: 56, type: "Meccan", hash: "" },
  { index: 75, name: "القيامة", englishName: "Al-Qiyamah", verses: 40, type: "Meccan", hash: "" },
  { index: 76, name: "الإنسان", englishName: "Al-Insan", verses: 31, type: "Medinan", hash: "" },
  { index: 77, name: "المرسلات", englishName: "Al-Mursalat", verses: 50, type: "Meccan", hash: "" },
  { index: 78, name: "النبأ", englishName: "An-Naba", verses: 40, type: "Meccan", hash: "" },
  { index: 79, name: "النازعات", englishName: "An-Nazi'at", verses: 46, type: "Meccan", hash: "" },
  { index: 80, name: "عبس", englishName: "'Abasa", verses: 42, type: "Meccan", hash: "" },
  { index: 81, name: "التكوير", englishName: "At-Takwir", verses: 29, type: "Meccan", hash: "" },
  { index: 82, name: "الانفطار", englishName: "Al-Infitar", verses: 19, type: "Meccan", hash: "" },
  { index: 83, name: "المطففين", englishName: "Al-Mutaffifin", verses: 36, type: "Meccan", hash: "" },
  { index: 84, name: "الانشقاق", englishName: "Al-Inshiqaq", verses: 25, type: "Meccan", hash: "" },
  { index: 85, name: "البروج", englishName: "Al-Buruj", verses: 22, type: "Meccan", hash: "" },
  { index: 86, name: "الطارق", englishName: "At-Tariq", verses: 17, type: "Meccan", hash: "" },
  { index: 87, name: "الأعلى", englishName: "Al-A'la", verses: 19, type: "Meccan", hash: "" },
  { index: 88, name: "الغاشية", englishName: "Al-Ghashiyah", verses: 26, type: "Meccan", hash: "" },
  { index: 89, name: "الفجر", englishName: "Al-Fajr", verses: 30, type: "Meccan", hash: "" },
  { index: 90, name: "البلد", englishName: "Al-Balad", verses: 20, type: "Meccan", hash: "" },
  { index: 91, name: "الشمس", englishName: "Ash-Shams", verses: 15, type: "Meccan", hash: "" },
  { index: 92, name: "الليل", englishName: "Al-Layl", verses: 21, type: "Meccan", hash: "" },
  { index: 93, name: "الضحى", englishName: "Ad-Duha", verses: 11, type: "Meccan", hash: "" },
  { index: 94, name: "الشرح", englishName: "Ash-Sharh", verses: 8, type: "Meccan", hash: "" },
  { index: 95, name: "التين", englishName: "At-Tin", verses: 8, type: "Meccan", hash: "" },
  { index: 96, name: "العلق", englishName: "Al-'Alaq", verses: 19, type: "Meccan", hash: "" },
  { index: 97, name: "القدر", englishName: "Al-Qadr", verses: 5, type: "Meccan", hash: "" },
  { index: 98, name: "البينة", englishName: "Al-Bayyinah", verses: 8, type: "Medinan", hash: "" },
  { index: 99, name: "الزلزلة", englishName: "Az-Zalzalah", verses: 8, type: "Medinan", hash: "" },
  { index: 100, name: "العاديات", englishName: "Al-'Adiyat", verses: 11, type: "Meccan", hash: "" },
  { index: 101, name: "القارعة", englishName: "Al-Qari'ah", verses: 11, type: "Meccan", hash: "" },
  { index: 102, name: "التكاثر", englishName: "At-Takathur", verses: 8, type: "Meccan", hash: "" },
  { index: 103, name: "العصر", englishName: "Al-'Asr", verses: 3, type: "Meccan", hash: "" },
  { index: 104, name: "الهمزة", englishName: "Al-Humazah", verses: 9, type: "Meccan", hash: "" },
  { index: 105, name: "الفيل", englishName: "Al-Fil", verses: 5, type: "Meccan", hash: "" },
  { index: 106, name: "قريش", englishName: "Quraysh", verses: 4, type: "Meccan", hash: "" },
  { index: 107, name: "الماعون", englishName: "Al-Ma'un", verses: 7, type: "Meccan", hash: "" },
  { index: 108, name: "الكوثر", englishName: "Al-Kawthar", verses: 3, type: "Meccan", hash: "" },
  { index: 109, name: "الكافرون", englishName: "Al-Kafirun", verses: 6, type: "Meccan", hash: "" },
  { index: 110, name: "النصر", englishName: "An-Nasr", verses: 3, type: "Medinan", hash: "" },
  { index: 111, name: "المسد", englishName: "Al-Masad", verses: 5, type: "Meccan", hash: "" },
  { index: 112, name: "الإخلاص", englishName: "Al-Ikhlas", verses: 4, type: "Meccan", hash: "" },
  { index: 113, name: "الفلق", englishName: "Al-Falaq", verses: 5, type: "Meccan", hash: "" },
  { index: 114, name: "الناس", englishName: "An-Nas", verses: 6, type: "Meccan", hash: "" },
];

// Complete hash filling based on a reproducible keccak256 hashing function
quranMetadataList.forEach((s) => {
  // Let's create a robust unique hash for each Surah based on its canonical metadata
  // In the real dApp, the hash matches the Keccak256 hash of the exact Arabic text of the Surah.
  const inputStr = `${s.index}-${s.name}-${s.englishName}-${s.verses}-${s.type}`;
  s.hash = ethers.keccak256(ethers.toUtf8Bytes(inputStr));
});
